/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RevenueAggregatorInterface extends ethers.utils.Interface {
  functions: {
    "withdrawPathErc20(address[],address,address)": FunctionFragment;
    "withdrawPathEth(address[],address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "withdrawPathErc20",
    values: [string[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPathEth",
    values: [string[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "withdrawPathErc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPathEth",
    data: BytesLike
  ): Result;

  events: {
    "WithdrawStatus(address,bool,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WithdrawStatus"): EventFragment;
}

export type WithdrawStatusEvent = TypedEvent<
  [string, boolean, string] & { path: string; status: boolean; result: string }
>;

export class RevenueAggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RevenueAggregatorInterface;

  functions: {
    withdrawPathErc20(
      paths: string[],
      targetWallet: string,
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawPathEth(
      paths: string[],
      targetWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  withdrawPathErc20(
    paths: string[],
    targetWallet: string,
    tokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawPathEth(
    paths: string[],
    targetWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    withdrawPathErc20(
      paths: string[],
      targetWallet: string,
      tokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawPathEth(
      paths: string[],
      targetWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "WithdrawStatus(address,bool,bytes)"(
      path?: string | null,
      status?: boolean | null,
      result?: null
    ): TypedEventFilter<
      [string, boolean, string],
      { path: string; status: boolean; result: string }
    >;

    WithdrawStatus(
      path?: string | null,
      status?: boolean | null,
      result?: null
    ): TypedEventFilter<
      [string, boolean, string],
      { path: string; status: boolean; result: string }
    >;
  };

  estimateGas: {
    withdrawPathErc20(
      paths: string[],
      targetWallet: string,
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawPathEth(
      paths: string[],
      targetWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    withdrawPathErc20(
      paths: string[],
      targetWallet: string,
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawPathEth(
      paths: string[],
      targetWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
