name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout solidity code.
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref}}
    - name: Install packages
      run: npm install
    - name: Run unit tests
      run:  npm run compile && npm run test
